name: Build, Test, and Deploy to Heroku

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: "Checkout code"
            uses: actions/checkout@v2

          - name: "Set up Node.js"
            uses: actions/setup-node@v2
            with:
                node-version: '22'

          - name: "Install dependencies"
            run: npm install

          - name: "Run tests"
            run: npm test

          - name: "Build project"
            run: npm run build

          - name: "Deploy to Heroku"
            uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
            with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
                heroku_email: ${{secrets.HEROKU_EMAIL}}